### ISSUE TITLE
Plugin settings ENV vars

### ISSUE THREAD

**Issue by hannahwoodward** [ournameismud/currency-layer#2]
It would be great if you could support ENV vars in the plugin settings - specifically with the API key.

**Comment by boldenamsterdam** [comment]
You can also achieve this by creating a config file for currency-layer inside the config folder

```./config/currency-layer.php```

with the following code

 ```<?php
return [
  'apiKey' => getenv('CURRENCY_LAYER_APIKEY'),
  'primaryCurrency' => getenv('CURRENCY_LAYER_PRIMARY_CURRENCY'),
  'apiCache' => false,
  'cacheDuration' => getenv('CURRENCY_LAYER_CACHE_DURATION'),
];
```

Hopefully this will help

**Comment by cole007** [comment]
To confirm ENV vars are supported with a plugin specific config file as pointed out by @boldenamsterdam 

@hannahwoodward marking this issue as closed

Cole
