### ISSUE TITLE
Error when API cache results is turned off

### ISSUE THREAD

**Issue by hannahwoodward** [ournameismud/currency-layer#3]
I had initially had some results cached, but wanted to test something with caching turned off. However, I got the following error:

```
Error
Cannot use object of type stdClass as array
```

which reported `ournameismud/currency-layer/src/services/Currency.php at line 46` as the culprit.

Craft Version: 3.4.18
Commerce Version: 3.1.3

**Comment by boldenamsterdam** [comment]
We created a [pull request that should fix this error](https://github.com/ournameismud/currency-layer/pull/4) 

Maybe you can use this fix in the meantime

**Comment by cole007** [comment]
Thanks for the PR @boldenamsterdam 

Indeed if caching was enabled it was not updating Commerce values on the initial lookup.
Additionally there was an issue with expecting the response as an array. Have added the line of code provided in the PR but also some other updates to provide fallbacks if the response is not in the expected format.

Cheers,

Cole
